version: "3"
services:
  mysql8.0:
    image: mysql:8.0
    container_name: mysql8_p001
    ports:
      - 127.0.0.1:3380:3306
    environment:
      - MYSQL_DATABASE=sakila
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql
      - MYSQL_ROOT_PASSWORD=mysql
      - TZ=UTC
    volumes:
      - ./db-volume:/var/lib/mysql
